### ISSUE TITLE
GW mointoring script is exiting sometime and causing docker exit.

### ISSUE THREAD

**Issue by govindsi** [tiiuae/mesh_com#153]
Sometime GW script is exiting and causing docker exit.

**Comment by Suhail-SSRC** [comment]
So the main thing is, I tried to delete the pre-installed mesh_com folder that is in the CM$ demo shrinked image. This is a part of the CI/CD to get the latest update of mesh_com, which is from the develop branch. Everything seems ok until you run ./start-docker sec_os from the latest develop branch as of today 19/05/2022. This is the output

![image](https://user-images.githubusercontent.com/96813754/169219396-71c30041-9147-40ee-82d1-9d1bae758383.png)

![image](https://user-images.githubusercontent.com/96813754/169219432-f9063ba5-5782-4555-ad92-c3c69cff12d0.png)

Somehow, it is giving back 2 ip addresses while it should be giving one. Govind and I think that ip address should be the gateway address

**Comment by joenpera** [comment]
I can check fix candidate for this one
