### ISSUE TITLE
mesh_ap SCC mode SYNC issue

### ISSUE THREAD

**Issue by Monika-Research** [tiiuae/mesh_com#219]
There is a synchronization issue between mesh setup using wpa-supplicant and soft ap configuration using hostapd.
Most of the time, the soft AP gets started before S9011sMesh completion.

Work around for this sync issue is suggested  here - https://github.com/tiiuae/mesh_com/commit/f91a3cb594869bcba2f87a6a4fd5f8289206ba02

**Comment by DamienDeMayaTII** [comment]
@mbaddeley, still relevant. If so, let's put in Jira, otherwise let's close this please.
