### ISSUE TITLE
Compatibility  eth+bridge in MS 1.5

### ISSUE THREAD

**Issue by martin-tii** [tiiuae/mesh_com#266]
MS1.5 does not support bridge + ethernet, due to the initialization of Mutual Auth as the first step.
To solve this, we should "switch off" the mutAuth as the first step, and then run `bridge_settings()` in the` entrypoint.sh.`
In this case, we will need to move the `features.yaml `to be read inside the` entrypoint.sh` --> maybe it can be added in the mesh.conf file

**Comment by joenpera** [comment]
In nats_integration branch we are adding eth0/eth1 to bridge based on the used device:
https://github.com/tiiuae/mesh_com/blob/nats_integration/common/scripts/mesh-11s.sh

And our nats_integration entrypoint.sh:
https://github.com/tiiuae/mesh_com/blob/nats_integration/modules/utils/docker/entrypoint.sh

Our default mesh.conf at the moment:
```
create_default_mesh_configuration() {

cat <<EOF >/opt/mesh_default.conf
# Modes: mesh, ap+mesh_scc, ap+mesh_mcc
MODE=mesh
IP=10.20.15.3
MASK=255.255.255.0
MAC=00:11:22:33:44:55
KEY=1234567890
ESSID=gold
FREQ=5805
FREQ_MCC=2412
TXPOWER=30
COUNTRY=AE
MESH_VIF=wlp1s0
PHY=phy0
ROUTING=batman-adv
ROLE=drone
PRIORITY=long_range
EOF
}

```

I hope that these can be integrated together some day as whole system containerization will be based on nats_integration branch entrypoint.sh file.

**Comment by DamienDeMayaTII** [comment]
Not relevant anymore. Also issues are tracked in Jira.
