### ISSUE TITLE
github actions are failing due to artifactory location change

### ISSUE THREAD

**Issue by govindsi** [tiiuae/mesh_com#270]
#9 7.455 E: Failed to fetch https://ssrc.jfrog.io/artifactory/ssrc-debian-public-remote/dists/focal/fog-sw/binary-amd64/Packages  404   [IP: 20.101.176.184 443]
#9 7.456 E: Some index files failed to download. They have been ignored, or old ones used instead.

ERROR: failed to solve: process "/bin/bash -c apt-get update -y && apt-get install -y --no-install-recommends     wpasupplicant=2.9.0-20-6~git20210701.43d8971     wifi-firmware     iw     batctl     alfred     rfkill     iproute2     && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100
Error: buildx failed with: ERROR: failed to solve: process "/bin/bash -c apt-get update -y && apt-get install -y --no-install-recommends     wpasupplicant=2.9.0-20-6~git20210701.43d8971     wifi-firmware     iw     batctl     alfred     rfkill     iproute2     && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100
/***********************************/

**Comment by maseabunikie** [comment]
There are fixes available for this issue in the branch:
https://github.com/tiiuae/mesh_com/blob/feat-doodle/modules/mesh_com/Dockerfile

In addition this line needs to be updated:
https://github.com/tiiuae/mesh_com/blob/feat-doodle/modules/mesh_com/Dockerfile.build_env#L30
Use the URL: https://ssrc.jfrog.io/artifactory/ssrc-deb-public-local

**Comment by maseabunikie** [comment]
Commits to be added are the following.
From: https://github.com/tiiuae/mesh_com/commit/b459d65a78359a43763f5e43e77b8c47e5ed8854
To: https://github.com/tiiuae/mesh_com/commit/73b3a424173812a758d74deb526addc95c555faa

Please, check the commits carefully because they might have conflicts.

**Comment by aravindraja93** [comment]
The Docker build succeeds, 

The deb build for Humble release is failing.

Tried updating the dists reference from focal->jammy locally,  in the modules/mesh_com/pacakge.sh

```
I: pybuild base:239: cd /mesh_com/sources/modules/mesh_com/.pybuild/cpython3_3.10/build; python3.10 -m pytest 
E: pybuild pybuild:369: test: plugin distutils failed with: exit code=5: cd /mesh_com/sources/modules/mesh_com/.pybuild/cpython3_3.10/build; python3.10 -m pytest 
dh_auto_test: error: pybuild --test --test-pytest -i python{version} -p 3.10 returned exit code 13
make[1]: *** [debian/rules:50: override_dh_auto_test] Error 25
make: *** [debian/rules:29: binary --parallel] Error 2
```

**Comment by aravindraja93** [comment]
https://github.com/tiiuae/mesh_com/pull/271
