### ISSUE TITLE
Duplicate copies of mesh configuration files

### ISSUE THREAD

**Issue by Monika-Research** [tiiuae/mesh_com#279]
Mesh configurations generally exist in a file mesh.conf @  /opt/container-data/mesh/mesh_com/.
Currently with mesh 1.5, this configuration file is being replaced by /opt/container-data/mesh/mesh_com/utils/docker/mesh.conf at startup. We may need to remove duplicate copies of config files and have a single one.

**Comment by DamienDeMayaTII** [comment]
Not relevant anymore. Also issues are tracked in Jira.
