### ISSUE TITLE
Interoperability issue with other Linux distro wrt os name.

### ISSUE THREAD

**Issue by govindsi** [tiiuae/mesh_com#36]
**Interoperability issue with other Linux distro wrt os name:**

Traceback (most recent call last):
  File "src/client-mesh.py", line 215, in <module>
    mac = get_mac_address(interface=get_mesh_interface())
  File "src/client-mesh.py", line 129, in get_mesh_interface
    return list(interface)[0]
IndexError: list index out of range

**Comment by martin-tii** [comment]
The current deployment is designed to be run on Ubuntu OS.
It will be needed to create another branch to deal with OpenWRT.
Other OSs are not considered.
