### ISSUE TITLE
Investigate best way to swap out and maintain different routing protocols (e.g., BATMAN, OLSR...) during build.

### ISSUE THREAD

**Issue by mbaddeley** [tiiuae/mesh_com#39]
- Investigate how to make the routing solution more generic and easy to swap out during build
- Investigate best way to modify exisiting routing protocols and include these within the rep (probably submodule)

**Comment by mbaddeley** [comment]
@joenpera Does this make sense to do this?

**Comment by DamienDeMayaTII** [comment]
Not relevant anymore. Also issues are tracked in Jira.
